---
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-71
  reek:
    enabled: true
  stylelint:
    enabled: true
    config:
      config: .stylelintrc
exclude_patterns:
- config/
- db/
- vendor/
- tmp/
- public/
- log/
- bin/
